# 除了通知开关其他的修改都要重启！！
# Other than the notification switch, all modifications need to be restarted!!

# 是否启用内置的 iptables 规则
# Is the built-in iptables rule enabled?
enable_iptables=true

# 阻断 ipv6 的 DNS 请求，仅在 enable_iptables=true 时生效
# Block DNS requests for IPv6, only effective when enable_iptables=True
block_ipv6_dns=true

# 重定向端口，请与 AdGuardHome 的设置保持一致
# Redirect port, please keep it consistent with AdGuardHome's settings
redir_port=5591

# 用户组和用户，用于绕过 AdGuardHome 本身
# User groups and users for bypassing AdGuardHome itself
adg_user=root
adg_group=net_raw

# 绕过目的地址列表，用空格分隔
# Bypass the list of destination addresses, separated by spaces
ignore_dest_list=""

# 绕过源地址列表，用空格分隔
# Bypass the list of source addresses, separated by spaces
ignore_src_list=""

# inotifyd 日志记录级别: 1=错误(ERROR) 2=警告(WARN) 3=信息(INFO) 4=调试(DEBUG)
# inotifyd log level: 1=ERROR 2=WARN 3=INFO 4=DEBUG
inotify_log_level=3

# 运行状态是否启用通知开关
# Is the notification switch enabled for the running status?
enable_notification=true

# 文件路径，请勿修改
# File path, do not modify
AGH_DIR="/data/adb/agh"
BIN_DIR="$AGH_DIR/bin"
SCRIPT_DIR="$AGH_DIR/scripts"
PID_FILE="$AGH_DIR/bin/agh.pid"
MOD_PATH="/data/adb/modules/AdGuardHome"
